export default {
	background1: require('../assets/images/background1.png'),
	background2: require('../assets/images/background2.png'),
	background3: require('../assets/images/background3.png'),
	background4: require('../assets/images/background4.png'),
	background5: require('../assets/images/background5.png'),
	background6: require('../assets/images/background6.png'),
	background7: require('../assets/images/background7.png'),
	background8: require('../assets/images/background8.png'),
	place1: require('../assets/images/place1.png'),
	place2: require('../assets/images/place2.png'),
	place3: require('../assets/images/place3.png'),
	avatar1: require('../assets/images/avatar1.png'),
	avatar2: require('../assets/images/avatar2.png'),
	avatar3: require('../assets/images/avatar3.png'),
}